---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDrACUDSIp+1x2OVfe3M84Kl69xI5cQ5NeTI31cLaMa9LuLOXl+p0NnAXZ4QEa1ivRZ0WI1ihXjhzMuezuqDD/dw5Bfn8qLfMfnK8eZW8Vo6IaBNu6PHzlxWkjkxgHFBtnc6h6LRGO0TkBYQm5XGVMyDcsWbedOPO923fbWmCtEJAyFQbBIWsyHkS/xwFfwatV+zWclS/WLHrD4/usNPZmVzWEY+JZr1cU9bWYjaXnQFaJaP2FZMFlMueuHu9uVnWP8fQDMNWkcOE6YJWtYQqPUGIvEJnC1P5Y6bIqcNa06U8IVMz1at5waSqwlk1SdmwzjgyZU8Q572/e3W/pdIwn71AG9+jbL2krUrwY3sA6CTGjs0JRY4t685RcE/A6yX2tNYg3q0WN0kpSzRPg5sdzPY+8cU9B+B1bBqkFTwn/2yQiAboXJp62fYwpAxQNT1KQNX1LIWUnLsBOVi2sa/QDEwiP0dkWvS2s4hflAJ7z7uGIiYPJ+3ql8m0RJnjfIUiVwAlMplQN4zpxTTzvi+mK/1Rmtv/jRhaUbj28zlqW5+ZMxpUv0Yhu60PpgsW+dJwz85GeK4U2A09P2DvTxV6EPi2GPTFj1K1pva5MSSTrfV3TQ2JVyJZOmeQ3I9tMjUsFWjD0uwAY4mvvjBculTOkSwURBqWysmfV2Jk1v8xXhiWu18CvqGzW6oOW/fl+lYUPN770bHMBAG9BCmU=
    admin-user: AgBrMRDLWSAw50cFNmcc9NzO9qhgzsjVlk9+ZDN1ZLwvZys6fS6u8dyNzWtvMRel5SoX/gAP/7Sfoz2q8E7Nk6PTK1kVkw+DGvmHUFW+lRCFE4Quie2VrPZ02fORKqvJcmXHXedehnC1teSPuXWML9/HsPg15MmmJPbIEVxAPZbeDfdY7zUENGIXGy1zuVC8zQ36S4U109EyDRjfbccAa3aPDCwAiwlo5E9Nkts+2SksZQNeE3oIgXNUI2Axt81jb1ADgA+0E4iraoSxtjkHMshCpGHHz2MgIR7hEJEiV7/HlmyjCJu5UxNabSaHFfPr2WMqc/hUzf1D2eUXh0TsWXglOsnabAaKciLwL9elcuuKJDGHReUvwSNpsbqASaxS7iS0CVOyeTy6O508cZPEP45LCkGG7U+btMRW5a1K2BdYRZtxGTwNtt1NEwaSzOR8g5WY3w2j5QRvMDQL/7gVLX7e6fMjlgl1Yz0Lm2xYiOrfGL/1rvEez0yTbHalVcSovoJvmX7S8hOoIsOLIPj5Zen6Hl3HVT6eAg7a0WxK1d/C+AWh/ki2RW2Gvl3pw7WFsBgPXe+h9B2d2tSg9xkzpRBU8AlJiJPPsakR6GkJA9Dv+fWfYoqC5EGID8colbEH8Lq7yhfG225PkB3mqLWzWIwVMFN2R7yc23P6gEFdCjDIQ8yvb5f9T70okKEP6chu6OOK/8SYMg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
