apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # قبل از monitoring sync بشه (monitoring روی wave 0 پیش‌فرض ـه)
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  # ساده‌ست - فقط manifestهای داخل پوشه رو apply می‌کنه
  source:
    repoURL: https://github.com/siraliebadi/homalab-gitops.git
    targetRevision: HEAD
    path: manifests/grafana-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true